
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!



target 'MyZhiBo' do
pod 'ViewUtils', '~> 1.1.2’
pod 'Masonry', '~> 0.6.3’
pod 'MQTTClient', '~> 0.7.9’
pod 'SDWebImage', '~>3.8.1'
pod 'JSONModel', '~>1.1.2'
#pod 'MJRefresh', '3.0.8'
pod 'IQKeyboardManager', '3.3.4'
pod 'TMCache', '2.1.0'

pod 'YYText'
pod 'YYImage'
pod 'LFLiveKit'
pod 'AFNetworking', '~> 3.1.0'
pod 'MQTTClient', '~> 0.7.9’

end


